### ISSUE TITLE
Problem with electron & ui-kitten

### ISSUE THREAD

**Issue by navneetccna** [codypearce/react-native-infinity#1]
Node: 8, 10, 12
OS: Linux

After running npm i getting following error

```
ERROR in ./electron/renderer.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-export-namespace-from' from '/home/owner/projects/RNETest/electron'
    at Function.module.exports [as sync] (/home/owner/projects/RNETest/node_modules/resolve/lib/sync.js:74:15)
    at resolveStandardizedName (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/owner/projects/RNETest/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/home/owner/projects/RNETest/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)


```

I manually installed  the package but after that I am getting following error when i am running npm run server

```
> AwesomeProject@0.0.1 server /home/owner/projects/RNETest
> webpack-dev-server --config ./electron/webpack.config.js

ℹ ｢wds｣: Project is running at http://localhost:7000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/owner/projects/RNETest/electron/src
✖ ｢wdm｣: Hash: 57d68d6e9828697271ea
Version: webpack 4.41.0
Time: 28718ms
Built at: 01/10/2019 11:43:51 am
    Asset      Size  Chunks             Chunk Names
bundle.js  2.93 MiB     app  [emitted]  app
Entrypoint app = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:7000 ./electron/renderer.js 40 bytes {app} [built]
[./electron/renderer.js] 694 bytes {app} [built]
[./node_modules/@babel/runtime/helpers/interopRequireDefault.js] 147 bytes {app} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[./node_modules/react/index.js] 190 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:7000] (webpack)-dev-server/client?http://localhost:7000 4.29 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.89 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {app} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {app} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {app} [built]
    + 363 hidden modules

ERROR in ./node_modules/react-native-ui-kitten/ui/layout/layout.component.js 108:16
Module parse failed: Unexpected token (108:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     render() {
|         const _a = this.props, { style, themedStyle } = _a, derivedProps = __rest(_a, ["style", "themedStyle"]);
>         return (<View {...derivedProps} style={[themedStyle, style]}/>);
|     }
| }
 @ ./node_modules/react-native-ui-kitten/ui/index.js 18:0-52 18:0-52
 @ ./node_modules/react-native-ui-kitten/index.js
 @ ./src/App.js
 @ ./electron/renderer.js

```

**Comment by navneetccna** [comment]
#2 will fix this issue

**Comment by navneetccna** [comment]
Closing this issue as fix is merged.
