### ISSUE TITLE
Error on Mac when start project

### ISSUE THREAD

**Issue by sarriaroman** [codypearce/react-native-infinity#3]
Command executed:

```react-native-infinity init MyProject --starter mwe --uilibrary m ```

Output:
```
Merging Package.json
/usr/local/lib/node_modules/react-native-infinity/node_modules/semver-set/lib/intersect.js:96
		return lo.test(hi.semver) && hi.test(lo.semver);
		          ^

TypeError: lo.test is not a function
    at /usr/local/lib/node_modules/react-native-infinity/node_modules/semver-set/lib/intersect.js:96:13
    at arrayFilter (/usr/local/lib/node_modules/react-native-infinity/node_modules/lodash/index.js:1384:13)
    at filter (/usr/local/lib/node_modules/react-native-infinity/node_modules/lodash/index.js:6309:14)
    at intersect (/usr/local/lib/node_modules/react-native-infinity/node_modules/semver-set/lib/intersect.js:92:11)
    at /usr/local/lib/node_modules/react-native-infinity/node_modules/merge-package-json/lib/merge.js:68:18
    at /usr/local/lib/node_modules/react-native-infinity/node_modules/lodash/internal/createObjectMapper.js:17:20
    at /usr/local/lib/node_modules/react-native-infinity/node_modules/lodash/internal/createBaseFor.js:19:11
    at baseForOwn (/usr/local/lib/node_modules/react-native-infinity/node_modules/lodash/internal/baseForOwn.js:14:10)
    at /usr/local/lib/node_modules/react-native-infinity/node_modules/lodash/internal/createObjectMapper.js:16:5
    at Object.updateDependencies (/usr/local/lib/node_modules/react-native-infinity/node_modules/merge-package-json/lib/merge.js:64:47)
```

**Comment by codypearce** [comment]
Hmm, I'm not having that issue locally. Could you try it with `npx`?

```
npx react-native-infinity init MyProject --starter mwe --uilibrary m
```
 
![image](https://user-images.githubusercontent.com/12564956/70731768-1af64d00-1cbc-11ea-8a51-5409af0c6d59.png)

**Comment by codypearce** [comment]
If you're still having trouble, please reopen this with more info, thanks!
